### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Cipher not initialized

### ISSUE THREAD

**Issue by yeyintkoko** [uxcam/react-native-ux-cam#33]
Hey I got this crash in v5.3.4.

```java
Fatal Exception: java.lang.IllegalStateException: Cipher not initialized
       at javax.crypto.Cipher.checkCipherState(Cipher.java:1326)
       at javax.crypto.Cipher.doFinal(Cipher.java:1733)
       at com.uxcam.internals.ck.a(:53)
       at com.uxcam.internals.cm.a(:27)
       at com.uxcam.internals.bv.a(:2)
       at com.uxcam.internals.ab.a(:8)
       at com.uxcam.internals.ab.c(:15)
       at com.uxcam.UXCam.startNewSession()
       at com.uxcam.RNUxcamModule.startNewSession(RNUxcamModule.java:77)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:764)
```

Could you please check?

**Comment by 3KINGZ** [comment]
@yeyintkoko were you able to find a solution for this?

**Comment by yeyintkoko** [comment]
> @yeyintkoko were you able to find a solution for this?

Yes, in our case we started recording on app active and stop recording when it goes background. When we remove that logic and start recording only on app launch, we don't have the crashes anymore.
