### ISSUE TITLE
Integrating UXCam shows  repetitive crashes in crashlytics

### ISSUE THREAD

**Issue by niranjanshk27** [uxcam/react-native-ux-cam#60]
I've done basic integration of UXCam and it started to show repetitive crashes in firebase crashlytics. Here is what the stack trace shows:

#### **`Fatal Exception: java.lang.StackOverflowError`**
```
Fatal Exception: java.lang.StackOverflowError: stack size 1039KB
       at com.uxcam.internals.he.a(SourceFile:24)
       at com.uxcam.internals.gu.a(SourceFile:30)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.fc.a(SourceFile:5)
       at com.uxcam.internals.gu.a(SourceFile:50)
       at com.uxcam.internals.gu.c(SourceFile:2)
       at com.uxcam.internals.hj.a(SourceFile:114)
       at com.uxcam.internals.hj.a(SourceFile:59)
       at com.uxcam.internals.gm.f(SourceFile:28)
       at com.uxcam.internals.gk.a(SourceFile:83)
       at com.uxcam.internals.-$$Lambda$jLwiVxd_MNJfiA6Nk-qOBcAFxxM.run(:4)
       at java.lang.Thread.run(Thread.java:919)
```

#### **`FrescoDecodeExecutor-6`**
```
FrescoDecodeExecutor-6
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       **at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:52)**
       at java.lang.Thread.run(Thread.java:919)
```
Here is a screenshot it might be helpful or might not Idk
![Bhoos-Games-–-he-line-24-–-Firebase-console](https://user-images.githubusercontent.com/11026689/181425330-7bfda346-ba00-41f3-9a85-4f46131341d1.png)

Details:
react-native: 0.66.1
react-native-ux-cam: ^5.4.0

**Comment by DFDIEGOH** [comment]
I apologize for the inconvenience @niranjanshk27 We will be releasing a new version of our React Native SDK that targets this specific crashes, I will keep you posted, but please let me know if you have further questions.

**Comment by niranjanshk27** [comment]
@DFDIEGOH Thank you for the response. Is there any timeline for the release? If you are releasing soon, we don't have to look for alternatives, otherwise, we have an urgent delivery.

**Comment by DFDIEGOH** [comment]
Hi @niranjanshk27 We expect to release a new version of our SDK by the end of this week or early next week, as soon as this is out I will let you know!

**Comment by DFDIEGOH** [comment]
Hi @niranjanshk27 I just wanted to mention that we have release a new version of our SDK that should fix this issue, Would it be possible if you upgrade to version 5.4.1 and check if this issue has been fixed? 

Please let me know

**Comment by shreysaroch** [comment]
@DFDIEGOH - on 5.4.1 i see many issues in crashlytics
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Surface.unlockCanvasAndPost(android.graphics.Canvas)' on a null object reference
       at com.uxcam.internals.gs$ad.a(gs.java:25)
       at com.uxcam.internals.gs$ad.lambda$MnbAfRnkGqdW03aZTF3iQDWKzk4(gs.java)
       at com.uxcam.b.-$$Lambda$fs$d$MnbAfRnkGqdW03aZTF3iQDWKzk4.a(-.java:4)
       at com.uxcam.internals.fm.a(fm.java:51)
       at com.uxcam.b.-$$Lambda$Qs6q2gU-jBXdoHn3va6ol-FOQT0.a(-.java:2)
       at com.uxcam.internals.fm.b(fm.java:14)
       at com.uxcam.b.-$$Lambda$OcigU9mjNbf1yjhZ_qJeX_lRwt8.a(-.java:10)
       at com.uxcam.internals.fm.a(fm.java:360)
       at com.uxcam.internals.fm.a(fm.java:306)
       at com.uxcam.b.-$$Lambda$kblyAoh5BCRes12b_5i_pR9fUSs.a(-.java:11)
       at com.uxcam.internals.fu.a(fu.java:167)
       at com.uxcam.b.-$$Lambda$3bOUek8Q-xo3VK52Axp14cTj0-8.a(-.java:6)
       at com.uxcam.internals.fu.a(fu.java:228)
       at com.uxcam.internals.fu.lambda$gKjChy34H2MtGMYS1g3PtZszHxM(fu.java)
       at com.uxcam.b.-$$Lambda$eu$gKjChy34H2MtGMYS1g3PtZszHxM.a(-.java:4)
       at com.uxcam.internals.eo.a(eo.java:71)
       at com.uxcam.internals.eo.lambda$fPmU2Rr_CHXwwVj5h4ffWrqHsSQ(eo.java)
       at com.uxcam.b.-$$Lambda$do$fPmU2Rr_CHXwwVj5h4ffWrqHsSQ.onPixelCopyFinished(-.java:6)
       at android.view.PixelCopy$1.run(PixelCopy.java:191)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

--------------------------------------------------------------------

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at com.uxcam.internals.iq.a(iq.java:10)
       at com.uxcam.internals.fu.a(fu.java:87)
       at com.uxcam.b.-$$Lambda$GobaCEoofLO76h0mdP9J3V8F1WI.run(-.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

--------------------------------------------------------------------

main (timed waiting): tid=1 systid=28815 
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1063)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1358)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
       at com.uxcam.internals.gk.a(gk.java:101)
       at com.uxcam.internals.hx.uncaughtException(hx.java:46)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
       at com.android.internal.os.RuntimeInitExtImpl.uncaughtExceptionExt(RuntimeInitExtImpl.java:43)
       at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:140)
       at java.lang.Thread.dispatchUncaughtException(Thread.java:2194)

**Comment by gabmadera** [comment]
Hello @shreysaroch these have been tackled on the latest SDK version, 5.4.2. Would it be possible to upgrade and let us know if this behaviour persists or indeed it's working as expected now? Thanks
