### ISSUE TITLE
Fatal Exception: AppLifecycleIntegration.removeObserver java.lang.NullPointerException - Parameter specified as non-null is null: method androidx.lifecycle.s.d, parameter observer

### ISSUE THREAD

**Issue by farhan-spinny** [uxcam/react-native-ux-cam#89]
Getting this crash on crashlytics on prod build for this version
"react-native-ux-cam": "5.4.6",

```
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.lifecycle.s.d,
 parameter observer        at androidx.lifecycle.LifecycleRegistry.removeObserver(LifecycleRegistry.kt:226)        at 
 io.sentry.android.core.AppLifecycleIntegration.removeObserver(AppLifecycleIntegration.java:97)        at 
 io.sentry.android.core.AppLifecycleIntegration.lambda$close$1(AppLifecycleIntegration.java)        at 
 android.os.Handler.handleCallback(Handler.java:942)


ft.a0 verify.uxcam.com:
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
       at okio.InputStreamSource.read(JvmOkio.kt:91)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
       at okio.RealBufferedSource.require(RealBufferedSource.kt)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt)
       at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt)
```

Any suggestions?

**Comment by gabrieluxcam** [comment]
Hello @farhan-spinny  would it be possible to test this using our latest SDK version 5.4.8? We've made several improvements and fixes since then and it may have solved directly your issue. 

Change log is available [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)

**Comment by DFDIEGOH** [comment]
close due to inactivity
